import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms and conditions for using MyShorts.",
  alternates: { canonical: "/terms" },
};

const UPDATED = "9 August 2026";

export default function Terms() {
  return (
    <article className="section article">
      <div className="wrap article-wrap">
        <h1>Terms of Service</h1>
        <p className="legal-updated">Last updated: {UPDATED}</p>
        <div className="article-body">
          <p>These Terms of Service (&ldquo;Terms&rdquo;) govern your use of the MyShorts website (myshorts.in) and application (app.myshorts.in) (together, the &ldquo;Service&rdquo;), operated by MyShorts (&ldquo;MyShorts&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;). By creating an account or using the Service, you agree to these Terms. If you do not agree, do not use the Service.</p>

          <h2>1. The Service</h2>
          <p>MyShorts is an AI tool that turns long-form YouTube videos into short vertical (9:16) clips, and generates summaries, notes, transcripts, and question-and-answer features for those videos. Features, limits, and plans may change over time.</p>

          <h2>2. Eligibility and accounts</h2>
          <p>You must be at least 18 years old to use the Service. You are responsible for keeping your account credentials secure and for all activity under your account. Provide accurate information and keep it up to date.</p>

          <h2>3. Your content and your responsibilities</h2>
          <p>You are solely responsible for the videos and links you submit and for how you use the output. By using the Service, you represent and warrant that:</p>
          <ul>
            <li>You own the necessary rights to the videos you process, or you have permission from the rights holder, or your use is otherwise permitted by law (for example, fair dealing/fair use).</li>
            <li>You will not use the Service to infringe copyright, trademark, privacy, or any other rights of a third party.</li>
            <li>You will not use the Service for unlawful, harmful, deceptive, or abusive purposes, or to create content that is illegal, defamatory, or violates any platform&rsquo;s rules.</li>
            <li>You will comply with the terms of any platform where you publish the output, including YouTube, Instagram, and TikTok.</li>
          </ul>
          <p>You retain ownership of the content you submit and the clips you create. We claim no ownership of your content; we only process it to provide the Service to you.</p>

          <h2>4. Third-party platforms and content</h2>
          <p>MyShorts is not affiliated with, endorsed by, or sponsored by YouTube or Google LLC. &ldquo;YouTube&rdquo; is a trademark of Google LLC. You are responsible for ensuring your use of third-party content complies with the rights holders&rsquo; and platforms&rsquo; terms. We are not responsible for third-party services the Service relies on or links to.</p>

          <h2>5. AI output</h2>
          <p>Clips, summaries, notes, and answers are generated by automated AI systems and may contain errors, omissions, or inaccuracies. You are responsible for reviewing output before publishing or relying on it. We do not guarantee that output is accurate, complete, or fit for any particular purpose.</p>

          <h2>6. Plans, billing, and cancellation</h2>
          <ul>
            <li>The Service offers a free plan and paid subscription plans (currently Creator at ₹499/month and Pro at ₹1,299/month). Prices and plan limits may change; changes will be reflected on the pricing page.</li>
            <li>Paid plans are billed on a recurring monthly basis through Razorpay and renew automatically until cancelled.</li>
            <li>You can cancel at any time; cancellation stops future renewals. Access to paid features continues until the end of the current billing period.</li>
            <li>Except where required by law, payments are non-refundable. Plan usage limits reset each billing cycle and do not roll over.</li>
          </ul>

          <h2>7. Acceptable use</h2>
          <p>You agree not to: reverse engineer, scrape, or overload the Service; resell or sublicense the Service without permission; bypass usage limits or security controls; or use the Service to process content you have no right to use. We may suspend or terminate accounts that violate these Terms.</p>

          <h2>8. Availability and changes</h2>
          <p>We aim to keep the Service available but do not guarantee uninterrupted or error-free operation. We may modify, suspend, or discontinue any part of the Service at any time.</p>

          <h2>9. Disclaimer of warranties</h2>
          <p>The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind, whether express or implied, including fitness for a particular purpose, merchantability, and non-infringement, to the maximum extent permitted by law.</p>

          <h2>10. Limitation of liability</h2>
          <p>To the maximum extent permitted by law, MyShorts and its team will not be liable for any indirect, incidental, special, consequential, or punitive damages, or for loss of profits, data, or goodwill. Our total liability for any claim relating to the Service will not exceed the amount you paid us in the three months before the claim arose.</p>

          <h2>11. Indemnification</h2>
          <p>You agree to indemnify and hold MyShorts harmless from any claims, damages, or costs arising from your use of the Service, your content, or your violation of these Terms or any third-party rights.</p>

          <h2>12. Termination</h2>
          <p>You may stop using the Service and delete your account at any time. We may suspend or terminate your access if you breach these Terms or use the Service unlawfully.</p>

          <h2>13. Governing law</h2>
          <p>These Terms are governed by the laws of India. You agree to the exclusive jurisdiction of the competent courts in India for any dispute arising out of or relating to these Terms or the Service.</p>

          <h2>14. Changes to these Terms</h2>
          <p>We may update these Terms from time to time. We will post the updated version here with a new &ldquo;Last updated&rdquo; date, and continued use of the Service after changes means you accept the updated Terms.</p>

          <h2>15. Contact us</h2>
          <p>Questions about these Terms? Email <a href="mailto:hello@myshorts.in">hello@myshorts.in</a>.</p>
        </div>
      </div>
    </article>
  );
}
